version: '3.8'
services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ~/docker/postgres/pgdata:/var/lib/postgresql/data/pgdata
#    secrets:
#      - postgres_password

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

#secrets:
#  postgres_password:
#    external: true
